import type { Product } from "./types";

function p(
  partial: Omit<Product, "imageAlt"> & { imageAlt?: string },
): Product {
  return {
    ...partial,
    imageAlt: partial.imageAlt ?? partial.name,
  };
}

export const mockProducts: Product[] = [
  // —— Pompe de căldură ——
  p({
    id: "hp-1",
    name: "Panasonic Aquarea 9 kW Bi-bloc",
    slug: "panasonic-aquarea-9kw",
    categorySlug: "instalatii-termice",
    subcategorySlug: "pompe-de-caldura",
    brand: "Panasonic",
    price: 18900,
    imageSrc: "/photo-product/Caparol-AerConditionat.jpeg",
    attrs: { brand: "panasonic", putere: "9-12", tip: "bi-bloc" },
  }),
  p({
    id: "hp-2",
    name: "Toshiba Estia 8 kW Mono-bloc",
    slug: "toshiba-estia-8kw",
    categorySlug: "instalatii-termice",
    subcategorySlug: "pompe-de-caldura",
    brand: "Toshiba",
    price: 16500,
    imageSrc: "/photo-product/Caparol-AerConditionat.jpeg",
    attrs: { brand: "toshiba", putere: "7-9", tip: "mono-bloc" },
  }),
  p({
    id: "hp-3",
    name: "Mitsubishi Electric Ecodan 14 kW",
    slug: "mitsubishi-ecodan-14kw",
    categorySlug: "instalatii-termice",
    subcategorySlug: "pompe-de-caldura",
    brand: "Mitsubishi Electric",
    price: 24500,
    imageSrc: "/photo-product/Caparol-AerConditionat.jpeg",
    attrs: { brand: "mitsubishi-electric", putere: "14-16", tip: "bi-bloc" },
  }),
  p({
    id: "hp-4",
    name: "Panasonic Aquarea 7 kW Mono-bloc",
    slug: "panasonic-aquarea-7kw",
    categorySlug: "instalatii-termice",
    subcategorySlug: "pompe-de-caldura",
    brand: "Panasonic",
    price: 15200,
    imageSrc: "/photo-product/Caparol-AerConditionat.jpeg",
    attrs: { brand: "panasonic", putere: "7-9", tip: "mono-bloc" },
  }),
  p({
    id: "hp-5",
    name: "Toshiba Estia 12 kW Bi-bloc",
    slug: "toshiba-estia-12kw",
    categorySlug: "instalatii-termice",
    subcategorySlug: "pompe-de-caldura",
    brand: "Toshiba",
    price: 21000,
    imageSrc: "/photo-product/Caparol-AerConditionat.jpeg",
    attrs: { brand: "toshiba", putere: "9-12", tip: "bi-bloc" },
  }),
  p({
    id: "hp-6",
    name: "Mitsubishi Electric Ecodan 16 kW",
    slug: "mitsubishi-ecodan-16kw",
    categorySlug: "instalatii-termice",
    subcategorySlug: "pompe-de-caldura",
    brand: "Mitsubishi Electric",
    price: 26800,
    imageSrc: "/photo-product/Caparol-AerConditionat.jpeg",
    attrs: { brand: "mitsubishi-electric", putere: "14-16", tip: "mono-bloc" },
  }),

  // —— Centrale termice ——
  p({
    id: "ct-1",
    name: "Buderus Logamax 24 kW cu boiler",
    slug: "buderus-logamax-24",
    categorySlug: "instalatii-termice",
    subcategorySlug: "centrale-termice",
    brand: "Buderus",
    price: 6200,
    imageSrc: "/photo-product/Caparol-Centrala.jpeg",
    attrs: { brand: "buderus", putere: "24-28", "tip-boiler": "cu-boiler" },
  }),
  p({
    id: "ct-2",
    name: "Bosch Condens 5300i 28 kW",
    slug: "bosch-condens-28",
    categorySlug: "instalatii-termice",
    subcategorySlug: "centrale-termice",
    brand: "Bosch",
    price: 5800,
    imageSrc: "/photo-product/Caparol-Centrala.jpeg",
    attrs: { brand: "bosch", putere: "24-28", "tip-boiler": "fara-boiler" },
  }),
  p({
    id: "ct-3",
    name: "Saunier Duval IsoFast 35 kW",
    slug: "saunier-isofast-35",
    categorySlug: "instalatii-termice",
    subcategorySlug: "centrale-termice",
    brand: "Saunier Duval",
    price: 7100,
    imageSrc: "/photo-product/Caparol-Centrala.jpeg",
    attrs: { brand: "saunier-duval", putere: "30-35", "tip-boiler": "cu-boiler" },
  }),
  p({
    id: "ct-4",
    name: "Buderus GB172 40 kW",
    slug: "buderus-gb172-40",
    categorySlug: "instalatii-termice",
    subcategorySlug: "centrale-termice",
    brand: "Buderus",
    price: 8900,
    imageSrc: "/photo-product/Caparol-Centrala.jpeg",
    attrs: { brand: "buderus", putere: "35-plus", "tip-boiler": "fara-boiler" },
  }),
  p({
    id: "ct-5",
    name: "Bosch Condens 7000i 32 kW cu boiler",
    slug: "bosch-condens-32",
    categorySlug: "instalatii-termice",
    subcategorySlug: "centrale-termice",
    brand: "Bosch",
    price: 7500,
    imageSrc: "/photo-product/Caparol-Centrala.jpeg",
    attrs: { brand: "bosch", putere: "30-35", "tip-boiler": "cu-boiler" },
  }),
  p({
    id: "ct-6",
    name: "Saunier Duval ThemaFast 26 kW",
    slug: "saunier-thema-26",
    categorySlug: "instalatii-termice",
    subcategorySlug: "centrale-termice",
    brand: "Saunier Duval",
    price: 5400,
    imageSrc: "/photo-product/Caparol-Centrala.jpeg",
    attrs: { brand: "saunier-duval", putere: "24-28", "tip-boiler": "fara-boiler" },
  }),

  // —— Aer condiționat ——
  p({
    id: "ac-1",
    name: "Panasonic Etherea 12000 Btu Alb",
    slug: "panasonic-etherea-12k",
    categorySlug: "instalatii-termice",
    subcategorySlug: "aer-conditionat",
    brand: "Panasonic",
    price: 3200,
    imageSrc: "/photo-product/Caparol-AerConditionatInterior.jpeg",
    attrs: { brand: "panasonic", putere: "12000", culoare: "alb" },
  }),
  p({
    id: "ac-2",
    name: "Toshiba Shorai Edge 9000 Btu Negru",
    slug: "toshiba-shorai-9k",
    categorySlug: "instalatii-termice",
    subcategorySlug: "aer-conditionat",
    brand: "Toshiba",
    price: 2900,
    imageSrc: "/photo-product/Caparol-AerConditionatInterior.jpeg",
    attrs: { brand: "toshiba", putere: "9000", culoare: "negru" },
  }),
  p({
    id: "ac-3",
    name: "Mitsubishi Electric MSZ 18000 Btu Alb",
    slug: "mitsubishi-msz-18k",
    categorySlug: "instalatii-termice",
    subcategorySlug: "aer-conditionat",
    brand: "Mitsubishi Electric",
    price: 4100,
    imageSrc: "/photo-product/Caparol-AerConditionatInterior.jpeg",
    attrs: { brand: "mitsubishi-electric", putere: "18000", culoare: "alb" },
  }),
  p({
    id: "ac-4",
    name: "Bosch Climate 24000 Btu Gri",
    slug: "bosch-climate-24k",
    categorySlug: "instalatii-termice",
    subcategorySlug: "aer-conditionat",
    brand: "Bosch",
    price: 4800,
    imageSrc: "/photo-product/Caparol-AerConditionatInterior.jpeg",
    attrs: { brand: "bosch", putere: "24000", culoare: "gri" },
  }),
  p({
    id: "ac-5",
    name: "Buderus Logano AC 12000 Btu Roșu",
    slug: "buderus-ac-12k",
    categorySlug: "instalatii-termice",
    subcategorySlug: "aer-conditionat",
    brand: "Buderus",
    price: 3500,
    imageSrc: "/photo-product/Caparol-AerConditionatInterior.jpeg",
    attrs: { brand: "buderus", putere: "12000", culoare: "rosu" },
  }),
  p({
    id: "ac-6",
    name: "Panasonic TZ 9000 Btu Alb",
    slug: "panasonic-tz-9k",
    categorySlug: "instalatii-termice",
    subcategorySlug: "aer-conditionat",
    brand: "Panasonic",
    price: 2700,
    imageSrc: "/photo-product/Caparol-AerConditionatInterior.jpeg",
    attrs: { brand: "panasonic", putere: "9000", culoare: "alb" },
  }),

  // —— Calorifere ——
  p({
    id: "cal-1",
    name: "Radox Horizontal Alb 600×1200",
    slug: "radox-h-alb",
    categorySlug: "instalatii-termice",
    subcategorySlug: "calorifere-decorative",
    brand: "Radox",
    price: 890,
    imageSrc: "/instalatii-termice.jpeg",
    attrs: { brand: "radox", culoare: "alb", orientare: "orizontal" },
  }),
  p({
    id: "cal-2",
    name: "Irsap Tesi Vertical Negru",
    slug: "irsap-tesi-v-negru",
    categorySlug: "instalatii-termice",
    subcategorySlug: "calorifere-decorative",
    brand: "Irsap",
    price: 1250,
    imageSrc: "/instalatii-termice.jpeg",
    attrs: { brand: "irsap", culoare: "negru", orientare: "vertical" },
  }),
  p({
    id: "cal-3",
    name: "Radox Vertical Multicolor",
    slug: "radox-v-multi",
    categorySlug: "instalatii-termice",
    subcategorySlug: "calorifere-decorative",
    brand: "Radox",
    price: 1100,
    imageSrc: "/instalatii-termice.jpeg",
    attrs: { brand: "radox", culoare: "multicolor", orientare: "vertical" },
  }),
  p({
    id: "cal-4",
    name: "Irsap Piano Horizontal Alb",
    slug: "irsap-piano-h",
    categorySlug: "instalatii-termice",
    subcategorySlug: "calorifere-decorative",
    brand: "Irsap",
    price: 980,
    imageSrc: "/instalatii-termice.jpeg",
    attrs: { brand: "irsap", culoare: "alb", orientare: "orizontal" },
  }),

  // —— Iluminat interior ——
  p({
    id: "ii-1",
    name: "Redo Spot LED interior",
    slug: "redo-spot-led",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-interior",
    brand: "Redo",
    price: 180,
    imageSrc: "/photo-product/Caparol-Becuri.jpeg",
    attrs: { brand: "redo" },
  }),
  p({
    id: "ii-2",
    name: "Arelux Plafonieră modernă",
    slug: "arelux-plafoniera",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-interior",
    brand: "Arelux",
    price: 320,
    imageSrc: "/photo-product/Caparol-Becuri.jpeg",
    attrs: { brand: "arelux" },
  }),
  p({
    id: "ii-3",
    name: "Redo Pendul living",
    slug: "redo-pendul",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-interior",
    brand: "Redo",
    price: 450,
    imageSrc: "/photo-product/Caparol-Becuri.jpeg",
    attrs: { brand: "redo" },
  }),
  p({
    id: "ii-4",
    name: "Arelux Bandă LED 5m",
    slug: "arelux-banda-led",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-interior",
    brand: "Arelux",
    price: 95,
    imageSrc: "/photo-product/Caparol-Becuri.jpeg",
    attrs: { brand: "arelux" },
  }),

  // —— Iluminat exterior ——
  p({
    id: "ie-1",
    name: "Redo Aplica fațadă IP65",
    slug: "redo-aplica-fatada",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-exterior",
    brand: "Redo",
    price: 210,
    imageSrc: "/photo-product/Caparol-Bec.jpeg",
    attrs: { brand: "redo" },
  }),
  p({
    id: "ie-2",
    name: "Arelux Stâlp grădină LED",
    slug: "arelux-stalp",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-exterior",
    brand: "Arelux",
    price: 380,
    imageSrc: "/photo-product/Caparol-Bec.jpeg",
    attrs: { brand: "arelux" },
  }),
  p({
    id: "ie-3",
    name: "Redo Proiector LED 50W",
    slug: "redo-proiector",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-exterior",
    brand: "Redo",
    price: 160,
    imageSrc: "/photo-product/Caparol-Bec.jpeg",
    attrs: { brand: "redo" },
  }),
  p({
    id: "ie-4",
    name: "Arelux Lampă solară",
    slug: "arelux-solara",
    categorySlug: "instalatii-termice",
    subcategorySlug: "iluminat-exterior",
    brand: "Arelux",
    price: 140,
    imageSrc: "/photo-product/Caparol-Bec.jpeg",
    attrs: { brand: "arelux" },
  }),

  // —— Prize ——
  p({
    id: "pr-1",
    name: "Vimar Plana priză Alb",
    slug: "vimar-plana-alb",
    categorySlug: "instalatii-termice",
    subcategorySlug: "prize-intrerupatoare",
    brand: "Vimar",
    price: 45,
    imageSrc: "/photo-product/Caparol-Priza.jpeg",
    attrs: { brand: "vimar", culoare: "alb" },
  }),
  p({
    id: "pr-2",
    name: "Ave Yes întrerupător Negru",
    slug: "ave-yes-negru",
    categorySlug: "instalatii-termice",
    subcategorySlug: "prize-intrerupatoare",
    brand: "Ave",
    price: 52,
    imageSrc: "/photo-product/Caparol-Priza.jpeg",
    attrs: { brand: "ave", culoare: "negru" },
  }),
  p({
    id: "pr-3",
    name: "Vimar Eikon priză Multicolor",
    slug: "vimar-eikon-multi",
    categorySlug: "instalatii-termice",
    subcategorySlug: "prize-intrerupatoare",
    brand: "Vimar",
    price: 78,
    imageSrc: "/photo-product/Caparol-Priza.jpeg",
    attrs: { brand: "vimar", culoare: "multicolor" },
  }),
  p({
    id: "pr-4",
    name: "Ave Life priză USB Alb",
    slug: "ave-life-usb",
    categorySlug: "instalatii-termice",
    subcategorySlug: "prize-intrerupatoare",
    brand: "Ave",
    price: 95,
    imageSrc: "/photo-product/Caparol-Priza.jpeg",
    attrs: { brand: "ave", culoare: "alb" },
  }),

  // —— Parchet ——
  p({
    id: "pa-1",
    name: "Kronotex SPC Stejar 5 mm",
    slug: "kronotex-spc-stejar",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Kronotex",
    price: 89,
    imageSrc: "/photo-product/Caparol-Parchet.jpeg",
    attrs: { tip: "spc", grosime: "4-7", brand: "kronotex" },
  }),
  p({
    id: "pa-2",
    name: "Falquon Laminat Nuc 8 mm",
    slug: "falquon-laminat-nuc",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Falquon",
    price: 72,
    imageSrc: "/photo-product/Caparol-Parchet2.jpeg",
    attrs: { tip: "laminat", grosime: "8-14", brand: "falquon" },
  }),
  p({
    id: "pa-3",
    name: "Kährs Triplustratificat Stejar 14 mm",
    slug: "kahrs-triplu-14",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Kährs",
    price: 145,
    imageSrc: "/photo-product/Caparol-Parchet.jpeg",
    attrs: { tip: "masiv-triplustratificat", grosime: "8-14", brand: "kahrs" },
  }),
  p({
    id: "pa-4",
    name: "Kronotex SPC Gri 6 mm",
    slug: "kronotex-spc-gri",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Kronotex",
    price: 95,
    imageSrc: "/photo-product/Caparol-Parchet.jpeg",
    attrs: { tip: "spc", grosime: "4-7", brand: "kronotex" },
  }),
  p({
    id: "pa-5",
    name: "Falquon SPC Alb 5 mm",
    slug: "falquon-spc-alb",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Falquon",
    price: 82,
    imageSrc: "/photo-product/Caparol-Parchet2.jpeg",
    attrs: { tip: "spc", grosime: "4-7", brand: "falquon" },
  }),
  p({
    id: "pa-6",
    name: "Plintă Kronotex Stejar",
    slug: "plinta-kronotex",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Kronotex",
    price: 28,
    imageSrc: "/photo-product/Caparol-Parchet2.jpeg",
    attrs: { tip: "accesorii", brand: "kronotex" },
  }),
  p({
    id: "pa-7",
    name: "Plintă Falquon Albă",
    slug: "plinta-falquon",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Falquon",
    price: 24,
    imageSrc: "/photo-product/Caparol-Parchet2.jpeg",
    attrs: { tip: "accesorii", brand: "falquon" },
  }),
  p({
    id: "pa-8",
    name: "Kährs Masiv Frasin 12 mm",
    slug: "kahrs-masiv-12",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "parchet",
    brand: "Kährs",
    price: 168,
    imageSrc: "/photo-product/Caparol-Parchet.jpeg",
    attrs: { tip: "masiv-triplustratificat", grosime: "8-14", brand: "kahrs" },
  }),

  // —— Gresie & Faianță ——
  p({
    id: "gf-1",
    name: "Alaplana Gresie Lucioasă 60×60",
    slug: "alaplana-gresie-lucioasa",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "gresie-faianta",
    brand: "Alaplana",
    price: 65,
    imageSrc: "/photo-product/Caparol-Baie.jpeg",
    attrs: { tip: "gresie", brand: "alaplana", textura: "lucioasa" },
  }),
  p({
    id: "gf-2",
    name: "Tau Ceramica Faianță Mată 30×60",
    slug: "tau-faianta-mata",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "gresie-faianta",
    brand: "Tau Ceramica",
    price: 48,
    imageSrc: "/photo-product/Caparol-Baie.jpeg",
    attrs: { tip: "faianta", brand: "tau-ceramica", textura: "mata" },
  }),
  p({
    id: "gf-3",
    name: "Alaplana Faianță Lucioasă 25×40",
    slug: "alaplana-faianta-lucioasa",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "gresie-faianta",
    brand: "Alaplana",
    price: 42,
    imageSrc: "/photo-product/Caparol-Baie.jpeg",
    attrs: { tip: "faianta", brand: "alaplana", textura: "lucioasa" },
  }),
  p({
    id: "gf-4",
    name: "Tau Ceramica Gresie Mată 80×80",
    slug: "tau-gresie-mata",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "gresie-faianta",
    brand: "Tau Ceramica",
    price: 78,
    imageSrc: "/photo-product/Caparol-Baie.jpeg",
    attrs: { tip: "gresie", brand: "tau-ceramica", textura: "mata" },
  }),
  p({
    id: "gf-5",
    name: "Alaplana Gresie Mată Exterior 60×60",
    slug: "alaplana-gresie-ext",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "gresie-faianta",
    brand: "Alaplana",
    price: 72,
    imageSrc: "/photo-product/Caparol-Baie.jpeg",
    attrs: { tip: "gresie", brand: "alaplana", textura: "mata" },
  }),
  p({
    id: "gf-6",
    name: "Tau Ceramica Faianță Lucioasă Baie",
    slug: "tau-faianta-lucioasa",
    categorySlug: "gresie-faianta-parchet",
    subcategorySlug: "gresie-faianta",
    brand: "Tau Ceramica",
    price: 55,
    imageSrc: "/photo-product/Caparol-Baie.jpeg",
    attrs: { tip: "faianta", brand: "tau-ceramica", textura: "lucioasa" },
  }),

  // —— Vopseluri ——
  p({
    id: "vo-1",
    name: "Caparol CapaMaXX Alb 10L",
    slug: "caparol-capamaxx",
    categorySlug: "vopseluri",
    subcategorySlug: "vopsele-interior",
    brand: "Caparol",
    price: 185,
    imageSrc: "/photo-product/Caparol-Vopsea2.jpeg",
    attrs: { brand: "caparol" },
  }),
  p({
    id: "vo-2",
    name: "Alpina Die Weisse 10L",
    slug: "alpina-weisse",
    categorySlug: "vopseluri",
    subcategorySlug: "vopsele-interior",
    brand: "Alpina",
    price: 140,
    imageSrc: "/photo-product/Caparol-Vopsea2.jpeg",
    attrs: { brand: "alpina" },
  }),
  p({
    id: "vo-3",
    name: "Caparol Indeko-plus 12.5L",
    slug: "caparol-indeko",
    categorySlug: "vopseluri",
    subcategorySlug: "vopsele-interior",
    brand: "Caparol",
    price: 220,
    imageSrc: "/photo-product/Caparol-Vopsea2.jpeg",
    attrs: { brand: "caparol" },
  }),
  p({
    id: "vo-4",
    name: "Alpina Renova 5L",
    slug: "alpina-renova",
    categorySlug: "vopseluri",
    subcategorySlug: "vopsele-interior",
    brand: "Alpina",
    price: 75,
    imageSrc: "/photo-product/Caparol-Vopsea2.jpeg",
    attrs: { brand: "alpina" },
  }),
  p({
    id: "td-1",
    name: "Caparol ArteLasur",
    slug: "caparol-artelasur",
    categorySlug: "vopseluri",
    subcategorySlug: "tehnici-decorative",
    brand: "Caparol",
    price: 310,
    imageSrc: "/photo-product/Caparol-Camera.jpeg",
    attrs: { brand: "caparol" },
  }),
  p({
    id: "td-2",
    name: "Caparol Metallocryl Interior",
    slug: "caparol-metallocryl",
    categorySlug: "vopseluri",
    subcategorySlug: "tehnici-decorative",
    brand: "Caparol",
    price: 280,
    imageSrc: "/photo-product/Caparol-Camera.jpeg",
    attrs: { brand: "caparol" },
  }),
  p({
    id: "td-3",
    name: "Caparol Stucco Decor",
    slug: "caparol-stucco",
    categorySlug: "vopseluri",
    subcategorySlug: "tehnici-decorative",
    brand: "Caparol",
    price: 350,
    imageSrc: "/photo-product/Caparol-noptiera.jpeg",
    attrs: { brand: "caparol" },
  }),
  p({
    id: "tf-1",
    name: "Caparol Capatect Tencuială",
    slug: "caparol-capatect",
    categorySlug: "vopseluri",
    subcategorySlug: "tencuieli-finisaje",
    brand: "Caparol",
    price: 95,
    imageSrc: "/photo-product/Caparol-noptiera.jpeg",
    attrs: { brand: "caparol" },
  }),
  p({
    id: "tf-2",
    name: "Alpina Structura Finisaj",
    slug: "alpina-structura",
    categorySlug: "vopseluri",
    subcategorySlug: "tencuieli-finisaje",
    brand: "Alpina",
    price: 68,
    imageSrc: "/photo-product/Caparol-noptiera.jpeg",
    attrs: { brand: "alpina" },
  }),
  p({
    id: "tf-3",
    name: "Caparol AmphiSilan Fassadenputz",
    slug: "caparol-amphisilan",
    categorySlug: "vopseluri",
    subcategorySlug: "tencuieli-finisaje",
    brand: "Caparol",
    price: 120,
    imageSrc: "/photo-product/Caparol-Camera.jpeg",
    attrs: { brand: "caparol" },
  }),
];

export function getProductsFor(
  categorySlug: string,
  subcategorySlug: string,
): Product[] {
  return mockProducts.filter(
    (p) =>
      p.categorySlug === categorySlug && p.subcategorySlug === subcategorySlug,
  );
}
